### ISSUE TITLE
MenuBox 관련 

### ISSUE THREAD

**Issue by jeongye01** [Goal-achievement-system/goal-achievement-system-frontend#21]
로그인이 된 상태임에도 멤버데이터가 없는 경우(멤버데이터가 아직 로드되지 않음), 메뉴박스에 로그인 전 상태가 순간적으로 나타남.
메뉴 박스에 로그인 된 상태인지 구분하는 프롭을 넣어서 멤버가 로딩되고 있는 화면을 따로 작성하는게 좋아보입니다!

=>새로고침할 때 마다 로그인 전 화면이 깜빡거리면서 나타남

**Comment by sancy1003** [comment]
아직 로딩처리를 해주지 않고 있었는데 로딩 UI 관련 라이브러리 찾아서 적용해보겠습니다 👍
