### ISSUE TITLE
Redux 사용 시 action에 대한 loading, result, error 처리 관련 이슈

### ISSUE THREAD

**Issue by sancy1003** [Goal-achievement-system/goal-achievement-system-frontend#26]
#### 문제
1. 하나의 slice 내에 여러가지 action이 생성됨에 따라서 slice의 state인 isLoading, error로는 어느 action의 로딩 상태, 에러인지 구별이 힘듭니다.
2. 비밀번호 수정, 목표 머니 충전 등 사용자의 요청을 완료했을 때 화면상에 성공 여부의 결과를 알리기위한 state가 필요합니다. 

#### 생각중인 해결 방안
1. loading 상태만 관리하는 loadingSlice를 따로 생성하여 action에 따른 로딩 상태 state를 불러 올 수 있도록 작업
2. response 상태를 관리하는 responseSlice를 생성하여 action에 따른 성공여부 or 에러 state를 불러 올 수 있도록 작업
***
작업중 위와 같은 문제가 발생해 우선 작업하려고하는데 해결방안이 괜찮으시면 진행하고 더 좋은 방안이 있으면 얘기해주세요!

**Comment by jeongye01** [comment]
우선 1번으로 진행하는게 좋을거 같습니다 ~

**Comment by ahn0min** [comment]
네 1번으로 진행하는 것이 좋아보이네요
