### ISSUE TITLE
React.lazy , Suspense , react-router-dom 을 이용한 코드분할 제안드립니다.

### ISSUE THREAD

**Issue by ahn0min** [Goal-achievement-system/goal-achievement-system-frontend#4]
# 제안사항
간편하고 확실하게 페이지별로 코드 스플리팅 할 수 있는 것 같아 제안드립니다.
한 번 가볍게 읽어보시고 아래에 comment 달아주세요 🤗

## 1. Router를 base로 code splitting 하여 불필요한 페이지 컴포넌트 Lazy Loading 하기
- React.lazy 함수는 import 구문을 실행하는 함수를 인자로 가진다.
- import 구문을 만나면 Webpack에서 여러개의 chunk 파일로 분할
- router에 의해 필요할 경우 해당 chunk 파일을 읽어들인다.
- Suspense는 lazy 함수가 load 되는 동안 다른 지정한 화면을 보여줄 수 있다.
> lazy 함수로 불러온 Component는 Suspense 하위에서만 렌더링 된다.

### 장점
- 페이지 로딩 속도를 개선할 수 있다.
- 더 나은 UX를 위한 스켈레톤 UI (?) 를 쉽게 적용할 수 있다?

![image](https://user-images.githubusercontent.com/89904226/169648466-2c988944-bd43-4018-b057-2e45172654e2.png)

# 2. v.18 에서 추가된 Suspense 기능
- 서버 사이드 렌더링 지원
- 동시 렌더링 지원

<br>

![스크린샷 2022-05-21 오후 8 03 01](https://user-images.githubusercontent.com/89904226/169648886-3686a82f-b8ce-45a7-b6d3-1e15e11f5aca.jpg)

## Reference
- [Route-based code splitting](https://ko.reactjs.org/docs/code-splitting.html#route-based-code-splitting)- 
- [React.lazy 및 Suspense를 사용한 코드 분할](https://web.dev/i18n/ko/code-splitting-suspense/)

**Comment by sancy1003** [comment]
라우터 단계에서부터 스플릿하는것도 좋아보이네요.
저는 찬성입니다🖐

**Comment by jeongye01** [comment]
네 라우터별로 스플리팅이 보편적인거 같더라고요 저도 찬성이용
