### ISSUE TITLE
baseTemplate 관련 2

### ISSUE THREAD

**Issue by jeongye01** [Goal-achievement-system/goal-achievement-system-frontend#46]
아래 코드에 padding을 x 방향으로 주셨는데 y방향도 주시는건 어떨까요. 다른 페이지 구현할 때는 못느꼈는데 회원가입이 길어서 모바일이나 노트북 환경에서 화면 끝에 닿아서 답답해 보이더라고요!

```
	<div className="main pc:max-w-[1200px] mx-auto px-[20px] pc:px-[0]">
			<Header />
			{children}
			<ModalSection />
        </div>

```

**Comment by ahn0min** [comment]
네 우선 `pb-[20px]` 을 추가했습니다. padding 값을 더 주고 싶으시면 수정하셔도 괜찮습니다!
