### ISSUE TITLE
react-router-dom 의 Router 관련 질문

### ISSUE THREAD

**Issue by ahn0min** [Goal-achievement-system/goal-achievement-system-frontend#8]
## 대상
![image](https://user-images.githubusercontent.com/89904226/169768466-75d10386-3e2e-4555-afb9-3f7765512d60.png)

## 질문
- route 의 element  속성을 사용하지 않으신 이유가 궁금합니다!
```js
<Route path={Path.home} element={<Home />} />
```

**Comment by jeongye01** [comment]
이유는 없습니다..ㅎㅎ element 쓰고 싶으시면 바꿔두셔도 됩니다

**Comment by jeongye01** [comment]
react router dom v6 이전 버전에서는 이전에 생성해둔 것 처럼 작성했었는데 6버전 부터는 element로 써야 겠네요 아직 수정안하셨으면 바꿔두겠습니다

**Comment by ahn0min** [comment]
확인 감사합니다.
